services:
  # Backend API service
  - type: web
    name: colmignoli-whist-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend/src && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
    
  # Frontend static site
  - type: web
    name: colmignoli-whist-frontend
    env: static
    buildCommand: |
      cd frontend && 
      npm install && 
      npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: colmignoli-whist-backend
          envVarKey: RENDER_EXTERNAL_URL
