services:
  # Backend API service
  - type: web
    name: colmignoli-whist-backend
    env: python
    region: frankfurt
    plan: free
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend/src && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        fromService:
          type: web
          name: colmignoli-whist-frontend
          envVarKey: RENDER_EXTERNAL_URL
    
  # Frontend static site
  - type: web
    name: colmignoli-whist-frontend
    env: static
    region: frankfurt
    buildCommand: |
      cd frontend && 
      npm install && 
      REACT_APP_API_URL=$RENDER_EXTERNAL_BACKEND_URL npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: RENDER_EXTERNAL_BACKEND_URL
        fromService:
          type: web
          name: colmignoli-whist-backend
          envVarKey: RENDER_EXTERNAL_URL
