services:
  # Backend API service
  - type: web
    name: colmignoli-whist-backend
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "10000"
      - key: FRONTEND_URL
        fromService:
          type: web
          name: colmignoli-whist-frontend
          envVarKey: RENDER_EXTERNAL_URL
    
  # Frontend static site
  - type: static
    name: colmignoli-whist-frontend
    buildCommand: cd frontend && npm install && REACT_APP_API_URL=$RENDER_EXTERNAL_BACKEND_URL npm run build
    publishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: RENDER_EXTERNAL_BACKEND_URL
        fromService:
          type: web
          name: colmignoli-whist-backend
          envVarKey: RENDER_EXTERNAL_URL
